project_name = "floats.app"

[tasks]
format = "swift format --in-place --recursive Sources"

build = "strudel build"
install = "strudel build --install"
release = "strudel build --install"
test = "swift test --skip PerformanceTests"
"test:all" = "swift test"

# sim = "strudel sim"
device = {
  command = "strudel run --device",
  env = {
    APPLE_SIGNING_IDENTITY = "axo://apple/developer/dev-cert",
    APPLE_API_ISSUER = "axo://apple/app-store-connect/api-issuer-id",
    APPLE_API_KEY = "axo://apple/app-store-admin/api-key-id",
    APPLE_API_KEY_PATH = "axo://apple/app-store-admin/api-key-path"
  }
}
