[[target]]
platform              = "macos"
app.name              = "floats"
app.bundle_id         = "com.breakfastlabs.floats"
app.version           = "0.1.0"
app.build_number      = "1"
build.icon.src        = "resources/balloon.png"
build.icon.background = "#FDE8A9"
dmg.background        = "#eee9db"
dmg.icon_text_size    = 15
